### ISSUE TITLE
Don't include flags twice

### ISSUE THREAD

**Issue by TangentFoxy** [Shuudoushi/BlackRibbon#1]
Agency flags are usable by the player. Having the same flag in both Agencies and Flags means the player will see two copies of the flag in game.
![wwwwwwwwwwwwwwwww](https://cloud.githubusercontent.com/assets/15093567/13380880/30007740-de02-11e5-9133-1c33da059950.png)

**Comment by Shuudoushi** [comment]
Yeah... That was a bit on me and a bit on github... I deleted the extra flag locally, but github didn't get the memo... It'll be fixed when I get the rockets I'm working on actually working and release 0.7

**Comment by TangentFoxy** [comment]
If I may ask another question since we're here, what's the point of the "missile bays"? They seem to just be reconfigured Mk2 bays. (I admit not looking closely at the difference, though I don't imagine it being much.)

**Comment by Shuudoushi** [comment]
Built in Radar, weapons manager ect. But other than than that, they were going to have rotary racks built into them, but that model kept exploding for some reason, but I found the built in modules to work well enough to just include them anyway.

**Comment by Shuudoushi** [comment]
Oh, and there's also the slight issue of me not knowing which license that part would then fall under, as I use MIT and Baha uses one of the CC license.

**Comment by TangentFoxy** [comment]
Ah, I like that idea for reducing part count. :)

As for licensing, which CC does he use? I'm usually pretty good at figuring that stuff out.

**Comment by TangentFoxy** [comment]
@Shuudoushi He uses CC-BY-SA 2.0, which due to the SA clause means that anything used there needs to be under the same license. I do not know if building off of his mod _alone_ means that yours has to be entirely under that license, or if you can just license the parts individually that directly use parts. I would recommend taking a look at the various other BD-derived mods' licenses for that info.

**Comment by Shuudoushi** [comment]
I got permission from him today to put it under my license. Well, really i traded making him a manu tab and flag and stuff for use of it, but hey lol

**Comment by TangentFoxy** [comment]
Well that's one way to do it. xD

**Comment by Shuudoushi** [comment]
There we go. This issue should now be resolved with the latest version. Missiles/rockets are a pain in the ass btw...
